apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ginga
  namespace: metallb-system
spec:
  addresses:
  - 172.19.0.100-172.19.0.105

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
spec:
  ipAddressPools:
  - ginga
