name: Update Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  update_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
