name: Create Tag

on:
  push:
    branches:
      - main
jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Create Tag
        run: |
          git config --global user.name ${{ secrets.GH_USER }}
          git tag -a v1.0.0 -m "Release v1.0.0"
          git push origin v1.0.0